config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :articles do
    resources :comments
  end

  root 'welcome#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
    has_many :comments
    validates :title, presence: true,
                      length: {minimum: 2}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    http_basic_authenticate_with name: "anna", password: "1234", except: [:index, :show]
    def index
        @articles = Article.all 
    end

    def show
        @article = Article.find(params[:id])
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        
       if(@article.save)
            redirect_to @article
       else
            render 'new'
       end
    end

    def edit
        @article = Article.find(params[:id])        
    end

    def update
        @article = Article.find(params[:id])     
        if(@article.update(article_params))
            redirect_to @article
       else
            render 'edit'
       end   
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        redirect_to articles_path        
    end

    private
        def article_params
            params.require(:article).permit(:title, :text)
        end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    http_basic_authenticate_with name: "anna", password: "1234", only: [:destroy]
    
    def create
        @article = Article.find(params[:article_id])
        @comments = @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end

    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article)
    end

    private def comment_params
        params.require(:comment).permit(:username, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<h1>Edit Post</h1></br>
<%= form_with scope: :article, url: article_path(@article), method: :patch, local: true do |form| %>
  <% if @article.errors.any? %>
    <% @article.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end  %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field(:title, {:class => 'form-control'}) %>
    </p>
   
    <p>
      <%= form.label :body %> <br>
      <%= form.text_field(:body, {:class => 'form-control'}) %>
    </p>
   
    <p>
      <%= form.submit({:class => 'btn btn-primary'}) %>
    </p>
  <% end %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

 <% @articles.each do |article| %>
   <div class="well" style="padding-top:30px">
     <h3><%= article.title %></h3>
     <p><%= article.text %></p>
     <p><%= link_to 'Read More', article_path(article), :class=> 'btn btn-default' %> </p>
   </div>
 <% end %>

app/views/articles/new.html.erb
<h1>Create a New Post</h1></br>
<%= form_with scope: :article, url: articles_path, local: true do |form| %>
  <% if @article.errors.any? %>
    <% @article.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end  %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field(:title, {:class => 'form-control'}) %>
    </p>
   
    <p>
      <%= form.label :body %> <br>
      <%= form.text_field(:body, {:class => 'form-control'}) %>
    </p>
   
    <p>
      <%= form.submit({:class => 'btn btn-primary'}) %>
    </p>
  <% end %>

app/views/articles/show.html.erb
<p>
<strong>Title:</strong>
<%= @article.title %>
</p>

<p>
<strong>Text:</strong>
<%= @article.text %>
</p>

<hr>
<%= link_to "Edit", edit_article_path(@article), :class => 'btn btn-warning' %>
<%= link_to "Delete", @article,
                    method: :delete,
                    data: {confirm: "Are you sure?"},
                    :class => 'btn btn-danger' %>
            

<hr>

<%= render 'comments/comments' %>
<%= render 'comments/comment-form' %>

app/views/comments/_comment-form.html.erb
<h5> Add Comment <h5>
<%= form_for([@article, @article.comments.build]) do |f| %>
    <p>
        <%= f.label :username %><br>
        <%= f.text_field(:username, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.label :body %><br>
        <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.submit({:class => 'btn btn-success'}) %>
    </p>
<% end %>

app/views/comments/_comments.html.erb
<h3>Comments</h3>
<% @article.comments.each do |comment| %>
    <div class="container" style="background-color:lightgrey">
        <p> <strong> <%= comment.username %> </strong> <%= comment.body %></p>
        <%= link_to '[X]', [comment.article, comment],
                                        method: :delete,
                                        data: { confirm: 'Are you sure?' } %></p>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" %>    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

  </head>

  <body>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="#">Simple Blog</a>
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item" style="padding-right:60px">
            <li style="padding-right:60px"> <%= link_to "Home", home_path %> </li>
          </li>
          <li class="nav-item">
            <li><%= link_to "Create Post", new_article_path %></li>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container" style="margin-top:100px">
      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to a dumb blog site!</h1>
<h3> I am learning Rails</h3> 
<h6>Bear with me</h6>